name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_HOME: /usr/lib/jvm/temurin-17-jdk
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 🟢 устанавливаем Gradle напрямую вместо wrapper
      - name: Setup Gradle manually
        uses: gradle/gradle-build-action@v3

      - name: Build APK
        run: gradle -p app assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ArmenianLearningApp
          path: app/build/outputs/apk/debug/app-debug.apk
